#!/bin/sh
set -e 

mkdir -p /var/local/

acme="/usr/local/ispconfig/interface/acme"

if [[ -L "$acme" && -d "$acme" ]]
then
    echo "$acme is a symlink to a directory"
else
    mv /usr/local/ispconfig/interface/acme		 /var/local/acme
fi
